"""add public_id PhotoORM

Revision ID: 2c1d24d059c0
Revises: dd3c579556c3
Create Date: 2024-05-19 11:25:27.686517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1d24d059c0'
down_revision: Union[str, None] = 'dd3c579556c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('public_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'photos', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='unique')
    op.drop_column('photos', 'public_id')
    # ### end Alembic commands ###
