"""Photo_qrurl

Revision ID: 4116971d5706
Revises: 703640d0b6fb
Create Date: 2024-05-21 13:34:46.878643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4116971d5706'
down_revision: Union[str, None] = '703640d0b6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('qrcode_url', sa.String(), nullable=True))
    op.alter_column('profiles', 'first_name',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'last_name',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=False)
    op.drop_column('photos', 'qrcode_url')
    # ### end Alembic commands ###
