"""Removed_email_from_ProfileORM

Revision ID: 703640d0b6fb
Revises: 7ed6cfa6a87c
Create Date: 2024-05-20 14:07:26.076018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703640d0b6fb'
down_revision: Union[str, None] = '7ed6cfa6a87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
