"""users_added_role_and_loggedin

Revision ID: dd3c579556c3
Revises: ca0a1948b71f
Create Date: 2024-05-18 13:56:09.220541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3c579556c3'
down_revision: Union[str, None] = 'ca0a1948b71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loggedin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'loggedin')
    # ### end Alembic commands ###
